
name: Build iOS XCFramework

on:
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency:
  group: ios-xcframework-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-xcframework:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt,clippy

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache target dir
        uses: actions/cache@v4
        with:
          path: |
            target
          key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Add iOS Rust targets
        run: |
          rustup target add aarch64-apple-ios aarch64-apple-ios-sim x86_64-apple-ios-sim

      - name: Install cbindgen
        run: cargo install cbindgen

      - name: Build Rust staticlibs for device and simulators
        run: |
          cargo build -p ffi --release --target aarch64-apple-ios
          cargo build -p ffi --release --target aarch64-apple-ios-sim
          cargo build -p ffi --release --target x86_64-apple-ios-sim

      - name: Prepare headers and simulator universal lib
        run: |
          mkdir -p ios/MicrogridApp/RustBridge
          cbindgen core/ffi -o ios/MicrogridApp/RustBridge/microgrid_ffi.h
          mkdir -p build/ios
          lipo -create \
            target/aarch64-apple-ios-sim/release/libffi.a \
            target/x86_64-apple-ios-sim/release/libffi.a \
            -output build/ios/libffi_sim_universal.a

      - name: Create XCFramework
        run: |
          xcodebuild -create-xcframework \
            -library target/aarch64-apple-ios/release/libffi.a -headers ios/MicrogridApp/RustBridge \
            -library build/ios/libffi_sim_universal.a -headers ios/MicrogridApp/RustBridge \
            -output build/MicrogridFFI.xcframework

      - name: Upload XCFramework and header
        uses: actions/upload-artifact@v4
        with:
          name: microgrid-xcframework
          path: |
            build/MicrogridFFI.xcframework
            ios/MicrogridApp/RustBridge/microgrid_ffi.h
